services:
  - type: web
    name: terrainvente
    env: docker
    plan: free

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        sync: false # ou valeur fixe

      - key: APP_URL
        value: https://terrainvente.onrender.com
